-- Resibook Guard: aprendizado privado e telemetria segura de lacunas de busca.
begin;

create extension if not exists pgcrypto;

create table if not exists public.never_miss_items (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  theme text not null check (length(btrim(theme)) between 2 and 120),
  mistake text not null check (length(btrim(mistake)) between 2 and 2000),
  correct_explanation text not null check (
    length(btrim(correct_explanation)) between 2 and 4000
  ),
  card text not null default '' check (length(card) <= 2000),
  mental_phrase text not null default '' check (length(mental_phrase) <= 500),
  origin text check (
    origin is null
    or origin in ('questao', 'plantao', 'prescricao', 'conduta')
  ),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists never_miss_items_set_updated_at
  on public.never_miss_items;
create trigger never_miss_items_set_updated_at
before update on public.never_miss_items
for each row execute function public.set_resibook_updated_at();

create index if not exists never_miss_items_user_updated_idx
  on public.never_miss_items (user_id, updated_at desc);
create index if not exists never_miss_items_user_origin_idx
  on public.never_miss_items (user_id, origin);

alter table public.never_miss_items enable row level security;
alter table public.never_miss_items force row level security;

drop policy if exists never_miss_own_select on public.never_miss_items;
drop policy if exists never_miss_own_insert on public.never_miss_items;
drop policy if exists never_miss_own_update on public.never_miss_items;
drop policy if exists never_miss_own_delete on public.never_miss_items;

create policy never_miss_own_select
  on public.never_miss_items
  for select to authenticated
  using (user_id = (select auth.uid()));

create policy never_miss_own_insert
  on public.never_miss_items
  for insert to authenticated
  with check (user_id = (select auth.uid()));

create policy never_miss_own_update
  on public.never_miss_items
  for update to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

create policy never_miss_own_delete
  on public.never_miss_items
  for delete to authenticated
  using (user_id = (select auth.uid()));

create table if not exists public.search_no_result_logs (
  id bigint generated by default as identity primary key,
  term text not null check (length(btrim(term)) between 2 and 80),
  user_id uuid references auth.users(id) on delete set null,
  context text not null check (
    context in ('global', 'condutas', 'calculadoras')
  ),
  created_at timestamptz not null default now()
);

create index if not exists search_no_result_logs_term_idx
  on public.search_no_result_logs (lower(term));
create index if not exists search_no_result_logs_created_idx
  on public.search_no_result_logs (created_at desc);
create index if not exists search_no_result_logs_context_created_idx
  on public.search_no_result_logs (context, created_at desc);

alter table public.search_no_result_logs enable row level security;
alter table public.search_no_result_logs force row level security;

drop policy if exists search_no_result_admin_select
  on public.search_no_result_logs;
drop policy if exists search_no_result_admin_delete
  on public.search_no_result_logs;

create policy search_no_result_admin_select
  on public.search_no_result_logs
  for select to authenticated
  using (public.is_resibook_admin());

create policy search_no_result_admin_delete
  on public.search_no_result_logs
  for delete to authenticated
  using (public.is_resibook_admin());

create or replace function public.record_search_no_result(
  p_term text,
  p_context text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_term text := btrim(regexp_replace(coalesce(p_term, ''), '\s+', ' ', 'g'));
begin
  if v_user_id is null then
    return;
  end if;

  if length(v_term) < 2 or length(v_term) > 80 then
    return;
  end if;

  if p_context not in ('global', 'condutas', 'calculadoras') then
    return;
  end if;

  if
    v_term ~ '@'
    or v_term ~ '[0-9]{7,}'
    or v_term ~ '[0-9]{1,2}[/\-][0-9]{1,2}[/\-][0-9]{2,4}'
    or lower(v_term) ~ '(cpf|cart[aã]o[[:space:]]+sus|prontu[aá]rio|telefone|celular|endere[cç]o|nascimento|e-?mail|paciente)'
  then
    return;
  end if;

  if exists (
    select 1
    from public.search_no_result_logs log
    where log.user_id = v_user_id
      and lower(log.term) = lower(v_term)
      and log.context = p_context
      and log.created_at >= now() - interval '15 minutes'
  ) then
    return;
  end if;

  insert into public.search_no_result_logs (term, user_id, context)
  values (v_term, v_user_id, p_context);
end;
$$;

revoke all on function public.record_search_no_result(text, text) from public;
grant execute on function public.record_search_no_result(text, text)
  to authenticated;

comment on table public.never_miss_items is
  'Registros privados do recurso Nunca Mais Errar, isolados por user_id.';
comment on table public.search_no_result_logs is
  'Termos sanitizados de buscas clínicas sem resultado; leitura exclusiva do administrador.';
comment on column public.search_no_result_logs.user_id is
  'Opcional no modelo para eventos futuros sem sessão; o fluxo autenticado grava o próprio auth.uid().';
comment on function public.record_search_no_result(text, text) is
  'Registra termo sanitizado sem resultado e deduplica por usuário/contexto durante 15 minutos.';

commit;
