-- Barreiras essenciais para IA clínica e webhooks de cobrança.
begin;

create extension if not exists pgcrypto;

create table if not exists public.ai_rate_limit_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  route text not null check (route in ('case-review', 'ecg-analyze')),
  created_at timestamptz not null default now()
);

create index if not exists ai_rate_limit_events_user_route_created_idx
  on public.ai_rate_limit_events (user_id, route, created_at desc);

alter table public.ai_rate_limit_events enable row level security;
alter table public.ai_rate_limit_events force row level security;

-- A tabela não é acessível diretamente pelo navegador. O consumo acontece por
-- uma função fechada, com limites definidos no banco (não pelo cliente).
revoke all on table public.ai_rate_limit_events from public, anon, authenticated;

create or replace function public.consume_ai_rate_limit(p_route text)
returns table (allowed boolean, retry_after_seconds integer)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_minute_limit integer;
  v_daily_limit integer;
  v_minute_count integer;
  v_daily_count integer;
begin
  if v_user_id is null then
    return query select false, 60;
    return;
  end if;

  case p_route
    when 'case-review' then
      v_minute_limit := 5;
      v_daily_limit := 30;
    when 'ecg-analyze' then
      v_minute_limit := 3;
      v_daily_limit := 20;
    else
      raise exception 'unsupported_ai_route';
  end case;

  -- Serializa apenas o par usuário/rota para impedir estouro por concorrência.
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(v_user_id::text || ':' || p_route, 0)
  );

  select count(*)::integer
    into v_minute_count
    from public.ai_rate_limit_events as event
   where event.user_id = v_user_id
     and event.route = p_route
     and event.created_at >= pg_catalog.now() - interval '1 minute';

  if v_minute_count >= v_minute_limit then
    return query select false, 60;
    return;
  end if;

  select count(*)::integer
    into v_daily_count
    from public.ai_rate_limit_events as event
   where event.user_id = v_user_id
     and event.route = p_route
     and event.created_at >= pg_catalog.now() - interval '24 hours';

  if v_daily_count >= v_daily_limit then
    return query select false, 3600;
    return;
  end if;

  insert into public.ai_rate_limit_events (user_id, route)
  values (v_user_id, p_route);

  -- Limpeza oportunista e limitada ao próprio usuário.
  delete from public.ai_rate_limit_events as event
   where event.user_id = v_user_id
     and event.created_at < pg_catalog.now() - interval '30 days';

  return query select true, 0;
end;
$$;

revoke all on function public.consume_ai_rate_limit(text) from public, anon;
grant execute on function public.consume_ai_rate_limit(text) to authenticated;

comment on table public.ai_rate_limit_events is
  'Contadores técnicos das rotas de IA; não armazena prompt, imagem ou dados clínicos.';
comment on function public.consume_ai_rate_limit(text) is
  'Consome atomicamente a cota de IA do usuário autenticado com limites definidos no servidor.';

create table if not exists public.billing_webhook_events (
  id uuid primary key default gen_random_uuid(),
  provider text not null default 'mercado_pago' check (provider = 'mercado_pago'),
  environment text not null check (environment in ('production', 'test')),
  provider_event_id text not null check (length(provider_event_id) between 3 and 240),
  notification_type text not null check (length(notification_type) between 2 and 80),
  provider_data_id text not null check (length(provider_data_id) between 1 and 240),
  status text not null default 'processing' check (status in ('processing', 'completed', 'failed')),
  outcome text check (outcome is null or length(outcome) <= 80),
  attempts integer not null default 1 check (attempts > 0),
  last_error_code text check (last_error_code is null or length(last_error_code) <= 80),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  processed_at timestamptz,
  unique (provider, environment, provider_event_id)
);

create index if not exists billing_webhook_events_status_updated_idx
  on public.billing_webhook_events (status, updated_at desc);

alter table public.billing_webhook_events enable row level security;
alter table public.billing_webhook_events force row level security;

-- Somente a service role do servidor escreve ou lê este ledger.
revoke all on table public.billing_webhook_events from public, anon, authenticated;

comment on table public.billing_webhook_events is
  'Ledger idempotente de webhooks; armazena apenas metadados técnicos do provedor.';

commit;
